name: Deploy Site

on:
  workflow_dispatch:
  release:
    # released: only latest release will trigger
    types: [released]

concurrency:
  group: '${{ github.workflow }} - ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  publish-site:
    # manual dispatch or released only @antv/l7 main package
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'release' &&
        startswith(github.event.release.tag_name, '@antv/l7@')
      )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm site:build
      - run: |
          cd site/dist
          git init
          git config --local user.name antv
          git config --local user.email antv@antfin.com
          git add .
          git commit -m "update by release action"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          directory: site/dist
          branch: gh-pages
          force: true

      # Deploy site successful notify, only trigger by bot release
      - name: Deploy site successful notify
        if: ${{ success() && github.event_name == 'release' }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "text",
              "text": {
                "content": "å®˜ç½‘éƒ¨ç½²æˆåŠŸ, è¯·æ‰‹åŠ¨åŒæ­¥é›¨ç‡•ç«™ç‚¹",
              }
            }

      # Deploy site failed notify, only trigger by bot release
      - name: ğŸ”Š Deploy failed notify
        if: ${{ failure()  && github.event_name == 'release' }}
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN }}
          ignoreError: true
          body: |
            {
              "msgtype": "link",
              "link": {
                "title": "ğŸš¨ å®˜ç½‘éƒ¨ç½²å¤±è´¥",
                "text": "ğŸ”— è¯·ç‚¹å‡»é“¾æ¥æŸ¥çœ‹å…·ä½“åŸå› , å°è¯•ç‚¹å‡»å³ä¸Šè§’ [Re-run all jobs] é‡è¯•, æˆ–è€…æ‰‹åŠ¨éƒ¨ç½² ğŸš‘",
                "messageUrl": "https://github.com/antvis/L7/actions/workflows/deploy-site.yml",
                "picUrl": ""
              }
            }
