name: Issue Welcome

on:
  issues:
    types: [opened]

jobs:
  issue-welcome:
    runs-on: ubuntu-latest
    steps:
      - name: welcome
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'welcome'
          token: ${{ secrets.GITHUB_TOKEN }}
          body: hi @${{ github.event.issue.user.login }}, welcome!
          labels: 'good first issue'
          issue-emoji: '+1'
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: check-star
        uses: gacts/is-stargazer@v1
        id: check-star
      - name: Add need star labels
        if: steps.check-star.outputs.is-stargazer != 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'ğŸŒŸ need star'
      - name: Create comment
        if: steps.check-star.outputs.is-stargazer != 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}, Please star this repo if you find it useful! Thanks :star:!
            ä½ å¥½ @${{ github.event.issue.user.login }}ã€‚ğŸŒŸ ç»™åŠ›æ”¯æŒä¸€ä¸‹å§ï¼å¦‚æœè¿™ä¸ªä»“åº“å¯¹ä½ æœ‰å¸®åŠ©ï¼Œåˆ«å¿˜äº†çŒ®ä¸Šä½ çš„å°æ˜Ÿæ˜Ÿ â­ï¼ä½ çš„æ¯ä¸€é¢—æ˜Ÿéƒ½æ˜¯å¯¹æˆ‘ä»¬åŠªåŠ›çš„æœ€ç¾å¥½è®¤å¯ï¼æ„Ÿè°¢ä½ çš„é—ªäº®èµèµï¼ğŸŒŸ
