name: Issue Labeled

on:
  issues:
    types: [labeled]

permissions:
  issues: write # for actions-cool/issues-helper to update issues

jobs:
  issue-labeled:
    if: github.actor != github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Need reproduce
        if: github.event.label.name == 'ğŸ¤” need reproduce'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a online reproduction by forking codesandbox of [@antv/l7 demo template](https://codesandbox.io/s/l7-demo-w4v6pr?file=/index.js) Issues labeled by `Need Reproduce` will be closed if no activities in 3 days.

            ä½ å¥½ @${{ github.event.issue.user.login }}, æˆ‘ä»¬éœ€è¦ä½ æä¾›ä¸€ä¸ªåœ¨çº¿çš„é‡ç°å®ä¾‹ä»¥ä¾¿äºæˆ‘ä»¬å¸®ä½ æ’æŸ¥é—®é¢˜ã€‚ä½ å¯ä»¥é€šè¿‡ç‚¹å‡»è¿™é‡Œåˆ›å»ºä¸€ä¸ª [@antv/l7 demo æ¨¡æ¿](https://codesandbox.io/s/l7-demo-w4v6pr?file=/index.js) 3 å¤©å†…æœªè·Ÿè¿›æ­¤ issue å°†ä¼šè¢«è‡ªåŠ¨å…³é—­ã€‚

            ![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to troubleshoot the problem. Please complete the issue description, provide gifs, screenshots, config, version. And explain the reproduction steps in detail. Thanks so much for your cooperation! The issue will be closed without any replay within 15 days.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æä¾› gif, æˆªå›¾, ä»£ç ç‰‡æ®µ, é…ç½®ä¿¡æ¯, ç‰ˆæœ¬å·, å¯å¤ç°é“¾æ¥ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢! 15 å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ã€‚

      - name: Invalid
        if: github.event.label.name == 'â›” invalid'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, please fill in the relevant information according to the issue template to facilitate communication efficiently. recommend you to read [å¦‚ä½•å‘å¼€æºé¡¹ç›®æäº¤æ— æ³•è§£ç­”çš„é—®é¢˜](https://zhuanlan.zhihu.com/p/25795393), Thanks so much!

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æ–¹ä¾¿å¤§å®¶é«˜æ•ˆæ²Ÿé€š, å¼ºçƒˆæ¨èä½ é˜…è¯»[å¦‚ä½•å‘å¼€æºé¡¹ç›®æäº¤æ— æ³•è§£ç­”çš„é—®é¢˜](https://zhuanlan.zhihu.com/p/25795393)ã€‚

      - name: Help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, We totally like your proposal/feedback. welcome to [send us a Pull Request](https://help.github.com/en/articles/creating-a-pull-request) to solve this problem and contribute to the open source project. After submitting the code, please send a Pull Request to the master branch. We will review it and look forward to your contribution.

            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼ŒåŒæ„ä½ çš„åé¦ˆï¼Œæ¬¢è¿ç›´æ¥åœ¨æ­¤ä»“åº“ [åˆ›å»ºä¸€ä¸ª Pull Request](https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) æ¥è§£å†³è¿™ä¸ªé—®é¢˜ï¼Œä¸ºå¼€æºé¡¹ç›®è´¡çŒ®ä¸€ä»½åŠ›é‡ã€‚æäº¤ä»£ç åï¼Œè¯·å°† Pull Request å‘åˆ° master åˆ†æ”¯ï¼Œæˆ‘ä»¬ä¼šè¿›è¡Œ Reviewï¼ŒæœŸå¾…æ‚¨çš„è´¡çŒ®ã€‚

            ![giphy](https://user-images.githubusercontent.com/507615/62342668-4735dc00-b51a-11e9-92a7-d46fbb1cc0c7.gif)
