name: PR Labeled

on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Need test case or docs
        if: github.event.label.name == 'ğŸ™ need test cases or docs'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, ä¸ºäº†è®©ä»£ç æ›´å¥å£®, è¯·è¡¥å……ç›¸åº”å•å…ƒæµ‹è¯•, å¦‚æœæœ‰ API æ”¹åŠ¨, è¯·ä¿®æ”¹ [ç›¸åº”çš„æ–‡æ¡£](https://github.com/antvis/L7/tree/master/packages/site)

            Hello, @${{ github.event.pull_request.user.login }}, Thanks for your contribution. In order to make the code more robust, please add the corresponding unit tests, and update the [docs](https://github.com/antvis/L7/tree/master/packages/site) if there are API changes.

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, è¯·æ ¹æ®æ¨¡æ¿å®Œå–„ PR æè¿°, å¹¶ç«™åœ¨ç”¨æˆ·çš„è§’åº¦è¯´æ˜å…¶æ”¹åŠ¨ç›®çš„å’Œè§£å†³äº†ä»€ä¹ˆé—®é¢˜ (è€Œéä½ çš„è§£å†³æ–¹å¼), ä»¥ä¾¿äºæˆ‘ä»¬å¯ä»¥æ›´å¥½çš„è¿›è¡Œ Code Review, åŒæ—¶è¯·ç¡®ä¿å·²å…³è”ç›¸åº” issue (å¦‚æœ‰), æ£€æŸ¥ä½ çš„ commit æ˜¯å¦æœ‰æè¿°æ¸…æ¥šä½ è¿™ä¸ª PR æ‰€åšçš„äº‹æƒ…ã€‚

            Hello, @${{ github.event.pull_request.user.login }}, Thanks for your contribution. Please improve the PR description based on the template, and explain the purpose of the change and the problems solved from the perspective of users (not your solution), so that we can conduct a better Code Review. At the same time, please make sure corresponding issue is associated (if any) Meanwhile, please check whether your commit clearly describes what you do as a PR.

      - name: Need modify commit msg
        if: github.event.label.name == 'ğŸ™ need modify commit msg'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ä½ å¥½ @${{ github.event.pull_request.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„è´¡çŒ®, æ›´æ–°æ—¥å¿—ä¼šæ ¹æ®æ¯ä¸ª PR çš„æäº¤ä¿¡æ¯è‡ªåŠ¨ç”Ÿæˆ, æ‰€ä»¥è¯·ä¿®æ”¹ (rebase) ä½ çš„ git æäº¤ä¿¡æ¯ (æ¯”å¦‚: `git rebase -i HEAD~1`), ç¡®ä¿å…¶åº”è¯¥è¨€ç®€æ„èµ…çš„è¯´æ˜å½“å‰çš„**æ”¹åŠ¨ç‚¹** (ä¾‹: `feat: è¡¨æ ¼å¢åŠ æ»šåŠ¨äº¤äº’`, `fix: ä¿®å¤ç‚¹å‡»å•å…ƒæ ¼åè¡¨æ ¼æ— æ³•æ»šåŠ¨`) è€Œä¸æ˜¯ (`fix: bug`, `feat: æ–°åŠŸèƒ½`), è¯·é¢å‘ç”¨æˆ·, è®©æ›´æ–°æ—¥å¿—å…·æœ‰è‰¯å¥½çš„å¯è¯»æ€§, è°¢è°¢!

            Hello, @${{ github.event.pull_request.user.login }}, Thanks for your contribution. The changelog log is automatically generated for each PR commit, so please rebase your git commit (eg. `git rebase -i HEAD~1`) and make sure that it should be brief and to the point about the current ** change ** (eg: `feat: Table added scrolling interaction`, `fix: fixed table can't scroll after clicking on the cell`) instead of (`fix: bug`, `feat: new feature`), please face to users, make update log with good readability, thank you!