name: Release Notify

on:
  release:
    # published: latest and pre release will trigger
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: DingTalk Release Notify
        uses: visiky/dingtalk-release-notify@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DING_TALK_TOKEN: ${{ secrets.DING_TALK_ACCESS_TOKEN}}
          notify_title: 'ğŸ‰ L7 å‘å¸ƒ release {release_tag} ğŸ‰'
          notify_body: '## { title } <hr /> { body } <hr />'
          notify_footer: 'å‰å¾€ [**L7 Releases**]({ release_url }) æŸ¥çœ‹å®Œæ•´ä¿¡æ¯.'
          at_all: false
          enable_prerelease: false
